version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Denver
    groups:
      next:
        update-types: [minor, patch]
        patterns:
          - next
          - react
          - react-dom
          - "@types/react*"
      cloudflare:
        update-types: [minor, patch]
        patterns:
          - wrangler
          - "@cloudflare/workers-types"
      aws:
        update-types: [minor, patch]
        patterns:
          - "@aws-sdk/*"
      lint-and-test:
        update-types: [minor, patch]
        patterns:
          - "@biomejs/*"
          - vitest
          - typescript
      other-compatible:
        patterns: ["*"]
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    labels:
      - area/infra
      - type/chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Denver
    labels:
      - area/infra
      - type/chore

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Denver
    labels:
      - area/infra
      - type/chore
