import { randomBytes } from "node:crypto";
import { chmod, readFile, writeFile } from "node:fs/promises";

function randomHex(bytes = 32) {
  return randomBytes(bytes).toString("hex");
}

function safeValue(value) {
  if (value.includes("\n") || value.includes("\r")) throw new Error("environment values may not contain newlines");
  return value;
}

function isLoopbackSiteAddress(input) {
  try {
    const parsed = new URL(input.includes("://") ? input : `https://${input}`);
    return parsed.hostname === "localhost"
      || parsed.hostname === "127.0.0.1"
      || parsed.hostname === "[::1]";
  } catch {
    return false;
  }
}

async function init(path) {
  const publicUrl = process.env.AXEL_PUBLIC_URL ?? "http://localhost:8080";
  const siteAddress = process.env.AXEL_SITE_ADDRESS ?? publicUrl;
  const prefix = process.env.AXEL_RESOURCE_PREFIX ?? `axel-selfhost-${randomHex(8)}`;
  const values = {
    AXEL_DEPLOYMENT_MODE: "self-hosted",
    AXEL_INSTALLATION_ID: randomHex(16),
    AXEL_SITE_ADDRESS: siteAddress,
    AXEL_PUBLIC_URL: publicUrl,
    AXEL_DELIVERY_PUBLIC_URL: process.env.AXEL_DELIVERY_PUBLIC_URL ?? publicUrl,
    AXEL_RESOURCE_PREFIX: prefix,
    AXEL_HTTP_PORT: process.env.AXEL_HTTP_PORT ?? "80",
    AXEL_HTTPS_PORT: process.env.AXEL_HTTPS_PORT ?? "443",
    AXEL_PUBLISH_PUBLIC_PORTS: process.env.AXEL_PUBLISH_PUBLIC_PORTS
      ?? (isLoopbackSiteAddress(siteAddress) ? "0" : "1"),
    AXEL_LOCAL_BIND_ADDRESS: process.env.AXEL_LOCAL_BIND_ADDRESS ?? "127.0.0.1",
    AXEL_LOCAL_PORT: process.env.AXEL_LOCAL_PORT ?? "8080",
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID ?? "",
    CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN ?? "",
    CLOUDFLARE_RUNTIME_API_TOKEN: process.env.CLOUDFLARE_RUNTIME_API_TOKEN ?? "",
    DELIVERY_QUEUE_ID: "",
    RAW_PAYLOAD_BUCKET: "",
    NEXT_PUBLIC_AXEL_INGEST_URL: process.env.NEXT_PUBLIC_AXEL_INGEST_URL ?? "",
    POSTGRES_PASSWORD: randomHex(24),
    CREDENTIALS_MASTER_KEY: randomHex(32),
    DELIVERY_SHARED_SECRET: randomHex(32),
    SOURCE_LOOKUP_SHARED_SECRET: randomHex(32),
    INGEST_ADMIN_TOKEN: randomHex(32),
    CRON_SECRET: randomHex(32),
    RESEND_API_KEY: process.env.RESEND_API_KEY ?? "",
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL ?? "",
  };
  const body = [
    "# Generated by ./scripts/axel-self-host init. Keep this file private.",
    ...Object.entries(values).map(([key, value]) => `${key}=${safeValue(value)}`),
    "",
  ].join("\n");
  await writeFile(path, body, { encoding: "utf8", mode: 0o600, flag: "wx" });
  await chmod(path, 0o600);
}

async function set(path, key, value) {
  if (!/^[A-Z][A-Z0-9_]*$/.test(key)) throw new Error(`invalid key: ${key}`);
  safeValue(value);
  let current = "";
  try {
    current = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  const lines = current.length > 0 ? current.split("\n") : [];
  const index = lines.findIndex((line) => line.startsWith(`${key}=`));
  if (index === -1) lines.push(`${key}=${value}`);
  else lines[index] = `${key}=${value}`;
  await writeFile(path, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
  await chmod(path, 0o600);
}

const [command, path, key, value] = process.argv.slice(2);
if (!command || !path) throw new Error("usage: env-file.mjs <init|set> <path> [key value]");
if (command === "init") await init(path);
else if (command === "set" && key && value !== undefined) await set(path, key, value);
else throw new Error("usage: env-file.mjs <init|set> <path> [key value]");
