/**
 * The only R2 object-key shapes used for durable raw event payloads.
 *
 * Queue messages and ClickHouse rows are data, not authority. Callers with an
 * account-wide R2 credential must validate a returned key against the tenant
 * and event context before issuing a storage request.
 */

const MAX_RAW_PAYLOAD_KEY_LENGTH = 2_048;
const ISO_DATE_SEGMENT = /^(\d{4})-(\d{2})-(\d{2})$/u;

export interface RawPayloadKeyExpectation {
  workspaceId: string;
  /** Exact event id. For pull objects this excludes the trailing `.json`. */
  eventId?: string;
  /** Exact pull-source id. Event objects do not encode a source id. */
  sourceId?: string;
}

export type CanonicalRawPayloadKey =
  | {
      kind: "event";
      workspaceId: string;
      eventId: string;
      layout: "provider" | "dated";
    }
  | {
      kind: "pull";
      workspaceId: string;
      sourceId: string;
      stream: string;
      eventId: string;
    };

/**
 * Parse a raw-payload key only when it exactly matches a shape generated by
 * ingest-worker or pull-worker. Empty segments, repeated separators, dot
 * segments, control characters, and invalid calendar dates fail closed.
 */
export function parseCanonicalRawPayloadKey(
  key: string,
): CanonicalRawPayloadKey | null {
  if (
    typeof key !== "string"
    || key.length === 0
    || key.length > MAX_RAW_PAYLOAD_KEY_LENGTH
  ) {
    return null;
  }

  const segments = key.split("/");
  if (segments.some(isUnsafeSegment)) return null;

  if (segments.length === 4 && segments[0] === "events") {
    const workspaceId = segments[1]!;
    const discriminator = segments[2]!;
    const eventId = segments[3]!;
    if (discriminator === "provider") {
      return { kind: "event", workspaceId, eventId, layout: "provider" };
    }
    if (isCalendarDate(discriminator)) {
      return { kind: "event", workspaceId, eventId, layout: "dated" };
    }
    return null;
  }

  if (segments.length === 5 && segments[0] === "pull") {
    const objectName = segments[4]!;
    if (!objectName.endsWith(".json")) return null;
    const eventId = objectName.slice(0, -".json".length);
    if (isUnsafeSegment(eventId)) return null;
    return {
      kind: "pull",
      workspaceId: segments[1]!,
      sourceId: segments[2]!,
      stream: segments[3]!,
      eventId,
    };
  }

  return null;
}

/**
 * Validate a canonical raw-payload key against trusted request or queue
 * context. Workspace and event comparisons are exact. A supplied source id is
 * also compared for pull objects, the only raw-key family that encodes it.
 */
export function isCanonicalRawPayloadKey(
  key: string,
  expected: RawPayloadKeyExpectation,
): boolean {
  const parsed = parseCanonicalRawPayloadKey(key);
  if (!parsed || parsed.workspaceId !== expected.workspaceId) return false;
  if (expected.eventId !== undefined && parsed.eventId !== expected.eventId) {
    return false;
  }
  if (
    parsed.kind === "pull"
    && expected.sourceId !== undefined
    && parsed.sourceId !== expected.sourceId
  ) {
    return false;
  }
  return true;
}

function isUnsafeSegment(segment: string): boolean {
  return segment.length === 0
    || segment === "."
    || segment === ".."
    || hasControlCharacter(segment);
}

function hasControlCharacter(value: string): boolean {
  for (const character of value) {
    const codePoint = character.codePointAt(0)!;
    if (codePoint <= 0x1f || (codePoint >= 0x7f && codePoint <= 0x9f)) {
      return true;
    }
  }
  return false;
}

function isCalendarDate(segment: string): boolean {
  const match = ISO_DATE_SEGMENT.exec(segment);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.getUTCFullYear() === year
    && date.getUTCMonth() === month - 1
    && date.getUTCDate() === day;
}
