import {
  captureException,
  operationalAlertSentryIdentity,
  type SentryClient,
} from "@axel/observability";
import type { AlertSink } from "@axel/router";

/**
 * Turn numeric operational threshold events into stable Sentry Issues. Alert
 * summaries and details are generated by Axel and contain no message bodies,
 * credentials, customer identifiers, or provider responses.
 */
export function createSentryAlertSink(client: SentryClient | null): AlertSink {
  return {
    async notify(event) {
      const identity = operationalAlertSentryIdentity(event);
      await captureException(client, new Error(identity.message), {
        level: event.severity === "critical" ? "error" : "warning",
        fingerprint: identity.fingerprint,
        tags: {
          component: "operational_alert",
          alert_rule: event.rule,
          alert_source: event.source,
          alert_severity: event.severity,
        },
        extra: {
          summary: event.summary,
          details: event.details,
          occurred_at: event.occurred_at,
        },
      });
    },
  };
}
