import {
  captureException,
  operationalAlertSentryIdentity,
  type SentryClient,
} from "@axel/observability";
import { externalAlertEvent, type AlertSink } from "@axel/router";

/**
 * Turn numeric operational threshold events into stable Sentry Issues. Alert
 * summaries and details are generated by Axel and contain no message bodies,
 * credentials, customer identifiers, or provider responses.
 */
export function createSentryAlertSink(client: SentryClient | null): AlertSink {
  return {
    async notify(event) {
      const safeEvent = externalAlertEvent(event);
      const identity = operationalAlertSentryIdentity(safeEvent);
      await captureException(client, new Error(identity.message), {
        level: safeEvent.severity === "critical" ? "error" : "warning",
        fingerprint: identity.fingerprint,
        tags: {
          component: "operational_alert",
          alert_rule: safeEvent.rule,
          alert_source: safeEvent.source,
          alert_severity: safeEvent.severity,
        },
        extra: {
          summary: safeEvent.summary,
          details: safeEvent.details,
          occurred_at: safeEvent.occurred_at,
        },
      });
    },
  };
}
